version: '3.8'

services:
  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - "61616:61616"  # JMS
      - "8161:8161"    # Web Console
    environment:
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
    networks:
      - event-driven-network

networks:
  event-driven-network:
    driver: bridge
